'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.296
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DdpyTools.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 // 中医药典
        '''阿胶	e&apos;jiao
        '''阿魏	a&apos;wei
        '''阿魏化痞膏	a&apos;wei&apos;hua&apos;pi&apos;gao
        '''矮地茶	ai&apos;di&apos;cha
        '''艾附暖宫丸	ai&apos;fu&apos;nuan&apos;gong&apos;wan
        '''艾叶	ai&apos;ye
        '''安坤赞育丸	an&apos;kun&apos;zan&apos;yu&apos;wan
        '''八角茴香	ba&apos;jiao&apos;hui&apos;xiang
        '''八角茴香油	ba&apos;jiao&apos;hui&apos;xiang&apos;you
        '''八正合剂	ba&apos;zheng&apos;he&apos;ji
        '''白扁豆	bai&apos;bian&apos;dou
        '''白芍	bai&apos;shao
        '''白术	bai&apos;zhu
        '''柏子仁	bai&apos;zi&apos;ren
        '''柏子养心丸	bai&apos;zi&apos;yang&apos;xin&apos;wan
        '''百合	bai&apos;he
        '''百合固金丸	bai&apos;he&apos;gu&apos;jin&apos;wan
        '''浓缩丸	nong&apos;suo&apos;wan
        '''薄荷	bo&apos;he
        '''薄荷脑	bo&apos;hen&apos;ao
        '''薄荷素油	bo&apos;he&apos;su&apos;you
        '''薄荷油	bo&apos;he&apos;you
        '''保和丸	bao&apos;he&apos;wan
        '''宝咳宁颗粒	bao&apos;ke&apos;ning&apos;ke&apos;li
        '''北沙参	bei&apos;sha&apos;shen
        '''扁蓄	bian&apos;xu
        '''合成龙脑	he&apos;cheng&apos;long&apos;nao
        '''参精止渴丸	shen&apos;ji [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 多音词库() As String
            Get
                Return ResourceManager.GetString("多音词库", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 卝	guan	guàn	4
        '''羋	mi	mǐ	8
        '''羐	ling	líng	10
        '''瑴	jue	jué	14
        '''彛	yi	yí	16
        '''龜	gui	guī	16
        '''彞	yi	yí	18
        '''龞	bie	biē	27
        '''丨	gun	gǔn	1
        '''丩	jiu	jiū	2
        '''丬	pan	pán	3
        '''丫	ya	yā	3
        '''丰	feng	fēng	4
        '''中	zhong	zhòng,zhōng	4
        '''丮	ji	jǐ	4
        '''丯	jie	jiè	4
        '''丱	guan	guàn	5
        '''卡	ka,qia	kǎ,qiǎ	5
        '''串	chuan,guan	chuàn,guàn	7
        '''丳	chan	chǎn	8
        '''卥	xi	xī	8
        '''临	lin	lín,lìn	9
        '''亅	jue	jué	1
        '''亊	shi	shì	7
        '''事	shi	shì	8
        '''乀	fu	fú	1
        '''乁	yi	yí	1
        '''丿	pie	piě	1
        '''乃	nai	nǎi	2
        '''乂	yi	yì	2
        '''乄	shi,me	shī,mē	2
        '''九	jiu	jiǔ	2
        '''亇	ma	mā	3
        '''久	jiu	jiǔ	3
        '''么	me	me	3
        '''乇	tuo	tuō	3
        '''乆	jiu	jiǔ	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定字典() As String
            Get
                Return ResourceManager.GetString("淡定字典", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property 淡定词序() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("淡定词序", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 阿炳	a&apos;bing
        '''阿爸	a&apos;ba
        '''阿坝	a&apos;ba
        '''阿伯	a&apos;bo
        '''阿鼻	a&apos;bi
        '''阿扁	a&apos;bian
        '''阿保	a&apos;bao
        '''阿谤	a&apos;bang
        '''阿比	a&apos;bi
        '''阿柄	a&apos;bing
        '''阿鼻地狱	a&apos;bi&apos;di&apos;yu
        '''阿鼻叫唤	a&apos;bi&apos;jiao&apos;huan
        '''阿波罗	a&apos;bo&apos;luo
        '''阿波罗计划	a&apos;bo&apos;luo&apos;ji&apos;hua
        '''阿巴拉契亚山脉	a&apos;ba&apos;la&apos;qi&apos;ya&apos;shan&apos;mai
        '''阿比让	a&apos;bi&apos;rang
        '''阿巴斯	a&apos;ba&apos;si
        '''阿坝县	a&apos;ba&apos;xian
        '''阿鼻狱	a&apos;bi&apos;yu
        '''阿坝州	a&apos;ba&apos;zhou
        '''阿坝镇	a&apos;ba&apos;zhen
        '''阿布扎比	a&apos;bu&apos;zha&apos;bi
        '''阿保之功	a&apos;bao&apos;zhi&apos;gong
        '''阿保之劳	a&apos;bao&apos;zhi&apos;lao
        '''阿茶	a&apos;cha
        '''阿从	a&apos;cong
        '''阿谄	a&apos;chan
        '''阿城市	a&apos;cheng&apos;shi
        '''阿昌族	a&apos;chang&apos;zu
        '''阿城镇	a&apos;cheng&apos;zhen
        '''阿斗	a&apos;dou
        '''阿爹	a&apos;die
        '''阿弟	a&apos;di
        '''阿大	a&apos;da
        '''吖啶	a&apos;ding
        '''阿堵	a&apos;du
        '''阿党	a&apos;dang
        '''阿殿	a&apos;dian [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定词库() As String
            Get
                Return ResourceManager.GetString("淡定词库", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
