'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.296
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DdpyTools.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 // 四字成语 8011 个 拼音正确
        '''哀哀父母	ai&apos;ai&apos;fu&apos;mu	1
        '''哀哀欲绝	ai&apos;ai&apos;yu&apos;jue	1
        '''爱别离苦	ai&apos;bie&apos;li&apos;ku	1
        '''哀兵必胜	ai&apos;bing&apos;bi&apos;sheng	1
        '''爱不忍释	ai&apos;bu&apos;ren&apos;shi	1
        '''爱不释手	ai&apos;bu&apos;shi&apos;shou	1
        '''爱才如渴	ai&apos;cai&apos;ru&apos;ke	1
        '''爱财如命	ai&apos;cai&apos;ru&apos;ming	1
        '''爱才若渴	ai&apos;cai&apos;ruo&apos;ke	1
        '''哀而不伤	ai&apos;er&apos;bu&apos;shang	1
        '''挨风缉缝	ai&apos;feng&apos;ji&apos;feng	1
        '''哀感天地	ai&apos;gan&apos;tian&apos;di	1
        '''哀感顽艳	ai&apos;gan&apos;wan&apos;yan	1
        '''哀感中年	ai&apos;gan&apos;zhong&apos;nian	1
        '''哀告宾服	ai&apos;gao&apos;bin&apos;fu	1
        '''爱国如家	ai&apos;guo&apos;ru&apos;jia	1
        '''爱鹤失众	ai&apos;he&apos;shi&apos;zhong	1
        '''哀鸿遍野	ai&apos;hong&apos;bian&apos;ye	1
        '''哀毁骨立	ai&apos;hui&apos;gu&apos;li	1
        '''挨家挨户	ai&apos;jia&apos;ai&apos;hu	1
        '''挨肩并足	ai&apos;jian&apos;bing&apos;zu	1
        '''挨肩擦膀	ai&apos;jian&apos;ca&apos; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 四字成语() As String
            Get
                Return ResourceManager.GetString("四字成语", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 卝	guan	guàn	4
        '''羋	mi	mǐ	8
        '''羐	ling	líng	10
        '''瑴	jue	jué	14
        '''彛	yi	yí	16
        '''龜	gui	guī	16
        '''彞	yi	yí	18
        '''龞	bie	biē	27
        '''丨	gun	gǔn	1
        '''丩	jiu	jiū	2
        '''丬	pan	pán	3
        '''丫	ya	yā	3
        '''丰	feng	fēng	4
        '''中	zhong	zhòng,zhōng	4
        '''丮	ji	jǐ	4
        '''丯	jie	jiè	4
        '''丱	guan	guàn	5
        '''卡	ka,qia	kǎ,qiǎ	5
        '''串	chuan,guan	chuàn,guàn	7
        '''丳	chan	chǎn	8
        '''卥	xi	xī	8
        '''临	lin	lín,lìn	9
        '''亅	jue	jué	1
        '''亊	shi	shì	7
        '''事	shi	shì	8
        '''乀	fu	fú	1
        '''乁	yi	yí	1
        '''丿	pie	piě	1
        '''乃	nai	nǎi	2
        '''乂	yi	yì	2
        '''乄	shi,me	shī,mē	2
        '''九	jiu	jiǔ	2
        '''亇	ma	mā	3
        '''久	jiu	jiǔ	3
        '''么	me	me	3
        '''乇	tuo	tuō	3
        '''乆	jiu	jiǔ	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定字典() As String
            Get
                Return ResourceManager.GetString("淡定字典", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 我们
        '''一个
        '''他是
        '''年底
        '''事后
        '''时间
        '''近日
        '''积分
        '''公司
        '''企业
        '''注册
        '''中国
        '''可以
        '''工作
        '''或者
        '''没有
        '''信息
        '''文章
        '''自己
        '''产品
        '''等级
        '''使用
        '''这个
        '''精华
        '''作者
        '''就是
        '''他们
        '''通过
        '''如果
        '''服务
        '''以及
        '''论坛
        '''提供
        '''管理
        '''要求
        '''状态
        '''问题
        '''系统
        '''阅读
        '''软件
        '''了哪
        '''聊以
        '''自己的
        '''帖子
        '''项目
        '''因为
        '''电话
        '''网站
        '''所以
        '''但是
        '''支持
        '''用户
        '''台州市
        '''已经
        '''同时
        '''一些
        '''威望
        '''得很
        '''发布
        '''方式
        '''内容
        '''这些
        '''设计
        '''价格
        '''我的
        '''根据
        '''技术
        '''能么
        '''北京
        '''作为
        '''具有
        '''需要
        '''现在
        '''选择
        '''活动
        '''其他
        '''应当
        '''下载
        '''权限
        '''市场
        '''地址
        '''的人
        '''包括
        '''本站
        '''最后
        '''由于
        '''还是
        '''目前
        '''因此
        '''来自
        '''国家
        '''你的
        '''在线
        '''发展
        '''功能
        '''这种
        '''单位
        '''专业
        '''会员
        '''对于
        '''门派
        '''学生
        '''所有
        '''以上
        '''什么
        '''相关
        '''回复
        '''开始
        '''品牌
        '''上海
        '''情况
        '''组织
        '''他的
        '''都是
        '''登录
        '''万元
        '''一种
        '''图片
        '''而且
        '''离线
        '''规定
        '''网络
        '''也是
        '''主题
        '''其中
        '''关于
        '''成为
        '''学习 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定词序() As String
            Get
                Return ResourceManager.GetString("淡定词序", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 阿爸	a&apos;ba
        '''阿坝	a&apos;ba
        '''阿伯	a&apos;bo
        '''阿扁	a&apos;bian
        '''阿波罗	a&apos;bo&apos;luo
        '''阿巴斯	a&apos;ba&apos;si
        '''阿坝县	a&apos;ba&apos;xian
        '''阿坝州	a&apos;ba&apos;zhou
        '''阿坝镇	a&apos;ba&apos;zhen
        '''阿布扎比	a&apos;bu&apos;zha&apos;bi
        '''阿城市	a&apos;cheng&apos;shi
        '''阿昌族	a&apos;chang&apos;zu
        '''阿城镇	a&apos;cheng&apos;zhen
        '''阿斗	a&apos;dou
        '''阿弟	a&apos;di
        '''阿达	a&apos;da
        '''阿呆	a&apos;dai
        '''阿德	a&apos;de
        '''阿迪	a&apos;di
        '''阿迪达斯	a&apos;di&apos;da&apos;si
        '''阿的平	a&apos;de&apos;ping
        '''阿杜瓦战役	a&apos;du&apos;wa&apos;zhan&apos;yi
        '''阿尔巴尼	a&apos;er&apos;ba&apos;ni
        '''阿尔巴尼亚	a&apos;er&apos;ba&apos;ni&apos;ya
        '''阿尔卑斯	a&apos;er&apos;bei&apos;si
        '''阿尔卑斯山	a&apos;er&apos;bei&apos;si&apos;shan
        '''阿尔卑斯山脉	a&apos;er&apos;bei&apos;si&apos;shan&apos;mai
        '''阿尔法	a&apos;er&apos;fa
        '''阿耳法粒子	a&apos;er&apos;fa&apos;li&apos;zi
        '''阿尔及利	a&apos;er&apos;ji&apos;li
        '''阿尔及利亚	a&apos;er&apos;ji&apos;li&apos;ya
        '''阿尔卡特	a&apos;er&apos;ka&apos;te
        '''阿尔山市	a&apos;er&apos;shan&apos;shi
        '''阿尔泰山 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定词库() As String
            Get
                Return ResourceManager.GetString("淡定词库", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
