'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.296
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DdpySrv.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 啊	a
        '''阿	a
        '''呵	a
        '''腌	a
        '''嗄	a
        '''锕	a
        '''吖	a
        '''錒	a
        '''嬶	a
        '''厑	a
        '''爱	ai
        '''碍	ai
        '''唉	ai
        '''哎	ai
        '''挨	ai
        '''埃	ai
        '''矮	ai
        '''艾	ai
        '''哀	ai
        '''蔼	ai
        '''癌	ai
        '''隘	ai
        '''霭	ai
        '''暧	ai
        '''嗳	ai
        '''捱	ai
        '''皑	ai
        '''噫	ai
        '''瑷	ai
        '''嫒	ai
        '''嗌	ai
        '''毐	ai
        '''僾	ai
        '''诶	ai
        '''锿	ai
        '''﨟	ai
        '''鴱	ai
        '''鱫	ai
        '''騃	ai
        '''馤	ai
        '''餲	ai
        '''靉	ai
        '''靄	ai
        '''阨	ai
        '''鑀	ai
        '''鎄	ai
        '''躷	ai
        '''譪	ai
        '''藹	ai
        '''薆	ai
        '''礙	ai
        '''硋	ai
        '''瞹	ai
        '''皧	ai
        '''皚	ai
        '''璦	ai
        '''濭	ai
        '''溾	ai
        '''溰	ai
        '''欸	ai
        '''曖	ai
        '''昹	ai
        '''敳	ai
        '''敱	ai
        '''懝	ai
        '''懓	ai
        '''愛	ai
        '''嬡	ai
        '''娾	ai
        '''娭	ai
        '''壒	ai
        '''塧	ai
        '''噯	ai
        '''嘊	ai
        '''啀	ai
        '''叆	ai
        '''佁	ai
        '''伌	ai
        '''魞	ai
        '''閊	ai
        '''砹	ai
        '''鱛	ai
        '''譺	ai
        '''凒	ai
        '''安	an
        '''按	an
        '''案	an
        ''' [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定字库() As String
            Get
                Return ResourceManager.GetString("淡定字库", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 我们	wo&apos;men
        '''一个	yi&apos;ge
        '''他是	ta&apos;shi
        '''年底	nian&apos;di
        '''事后	shi&apos;hou
        '''时间	shi&apos;jian
        '''近日	jin&apos;ri
        '''积分	ji&apos;fen
        '''公司	gong&apos;si
        '''企业	qi&apos;ye
        '''注册	zhu&apos;ce
        '''中国	zhong&apos;guo
        '''可以	ke&apos;yi
        '''工作	gong&apos;zuo
        '''或者	huo&apos;zhe
        '''没有	mei&apos;you
        '''信息	xin&apos;xi
        '''文章	wen&apos;zhang
        '''自己	zi&apos;ji
        '''产品	chan&apos;pin
        '''等级	deng&apos;ji
        '''使用	shi&apos;yong
        '''这个	zhe&apos;ge
        '''精华	jing&apos;hua
        '''作者	zuo&apos;zhe
        '''就是	jiu&apos;shi
        '''他们	ta&apos;men
        '''通过	tong&apos;guo
        '''如果	ru&apos;guo
        '''服务	fu&apos;wu
        '''以及	yi&apos;ji
        '''论坛	lun&apos;tan
        '''提供	ti&apos;gong
        '''管理	guan&apos;li
        '''要求	yao&apos;qiu
        '''状态	zhuang&apos;tai
        '''问题	wen&apos;ti
        '''系统	xi&apos;tong
        '''阅读	yue&apos;du
        '''软件	ruan&apos;jian
        '''聊以	liao&apos;yi
        '''自己的	zi&apos;ji&apos;de
        '''帖子	tie&apos;zi
        '''项目	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定词库() As String
            Get
                Return ResourceManager.GetString("淡定词库", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
