'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.296
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DdpySrv.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 // 张仲景伤寒论条文例
        '''function execZj(codes)
        '''{
        '''	var i = 1;
        '''	var aryRet = new Array();
        '''	var cd = codes.substring(2);
        '''
        '''	if ( cd.isBlank() ) {
        '''		aryRet[&quot;Tip&quot;] = &quot;请输入条文编号 1～398&quot;;
        '''    }else if (cd == i++) {
        '''        aryRet[aryRet.length] = ddpyCreateCand(&quot;1、太阳之为病，脉浮，头项强痛而恶寒。&quot;, null, 0);
        '''    }else if (cd == i++) {
        '''        aryRet[aryRet.length] = ddpyCreateCand(&quot;2、太阳病，发热汗出，恶风，脉缓者，名为中风。&quot;, null, 0);
        '''    }else if (cd == i++) {
        '''        aryRet[aryRet.length] = ddpyCreateCand(&quot;3、太阳病，或已发热，或未发热，必恶寒，体痛，呕逆，脉阴阳俱紧者，名为伤寒。&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property i伤寒论条文() As String
            Get
                Return ResourceManager.GetString("i伤寒论条文", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 // 伤寒金匮经方例
        '''function execJf(codes)
        '''{
        '''	var bFlg = false;
        '''	var aryRet = new Array();
        '''	var cd = codes.substring(2);
        '''
        '''	if ( !cd.isBlank() ) {
        '''		var oData = getJfObject();
        '''
        '''		for (var key in oData) {
        '''			if ( key == cd ){
        '''				aryRet[aryRet.length] = ddpyCreateCand(oData[key][1], null, 0);
        '''				bFlg = true;
        '''			}else if ( key.startWith(cd) ){
        '''				aryRet[aryRet.length] = ddpyCreateCand(oData[key][0], key.substring(cd.length));
        '''				bFlg = true;
        '''			}
        '''		}
        '''		
        '''		if ( !bFlg ){
        '''			aryRet[&quot;Tip&quot;] = &quot;你要的东东没 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property i伤寒金匮经方() As String
            Get
                Return ResourceManager.GetString("i伤寒金匮经方", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 // 日文汉字拼音输入
        '''function execRw(codes)
        '''{
        '''    var aryRet = new Array();
        '''    var cd = codes.substring(2);
        '''
        '''    if ( cd.isBlank() ){
        '''        aryRet[&quot;Tip&quot;] = &quot;请输入单字拼音全拼&quot;;
        '''    }else if ( cd == &quot;a&quot; ){
        '''        aryRet = createRwCand(&quot;a&quot;, &quot;阿&quot;);
        '''    }else if ( cd == &quot;ai&quot; ){
        '''        aryRet = createRwCand(&quot;ai&quot;, &quot;隘愛碍艾矮藹癌皚哀挨埃&quot;);
        '''    }else if ( cd == &quot;an&quot; ){
        '''        aryRet = createRwCand(&quot;an&quot;, &quot;鞍案岸暗按俺安&quot;);
        '''    }else if ( cd == &quot;ang&quot; ){
        '''        aryRet = createRwCand(&quot;ang&quot;, &quot;昂&quot;);
        '''    }else if ( cd == &quot;ao&quot; ){
        '''    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property i日文汉字拼音输入() As String
            Get
                Return ResourceManager.GetString("i日文汉字拼音输入", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /*
        '''// ----------------------------------------
        '''【方法名】ddpyRegisterCommand
        '''【概要】注册方法
        '''【参数】
        '''sCmd：编码栏作为拼音输入的命令 [必须]
        '''sName：候选中作为文本显示的名称 [必须]
        '''sMethod：对应的方法名 [必须]
        '''sTip：有值时忽略候选项仅显示该提示 [可选，默认无提示]
        '''sTitle：输入法窗口标题 [可选，默认不设定标题]
        '''hasDigitComp：是否把数字作为编码输入 [可选，默认主键盘数字键为非编码]
        '''【返回值】无
        '''
        '''
        '''【方法名】ddpyCreateCand
        '''【概要】创建一个候选项
        '''【参数】
        '''sText：候选项文本（&lt;br&gt;表示换行） [必须]
        '''sPy：候选项编码 [可选，默认空白串]
        '''bShowDigit：该候选项是否附加显示数字编号显示 [可选，默认附加显示数字编号]
        '''sDispText：候选项显示用文本（&lt;br&gt;表示换行） [可选，默认显示候选项文本]
        '''【返回值】候选项对象
        '''// --------------------------------------- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property i淡定脚本() As String
            Get
                Return ResourceManager.GetString("i淡定脚本", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 // 神农本草例
        '''function execBc(codes)
        '''{
        '''	var bFlg = false;
        '''	var aryRet = new Array();
        '''	var cd = codes.substring(2);
        '''
        '''	if ( !cd.isBlank() ) {
        '''		var oData = getBcObject();
        '''
        '''		for (var key in oData) {
        '''			if ( key == cd ){
        '''				aryRet[aryRet.length] = ddpyCreateCand(oData[key][1], null, 0);
        '''				bFlg = true;
        '''			}else if ( key.startWith(cd) ){
        '''				aryRet[aryRet.length] = ddpyCreateCand(oData[key][0], key.substring(cd.length));
        '''				bFlg = true;
        '''			}
        '''		}
        '''		
        '''		if ( !bFlg ){
        '''			aryRet[&quot;Tip&quot;] = &quot;你要的东东没找到 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property i神农本草() As String
            Get
                Return ResourceManager.GetString("i神农本草", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 // 符号输入用脚本例子，编码栏输入“ifh”时被调用
        '''//（codes为不包含第一位“i”的编码）
        '''function execFh(codes)
        '''{
        '''	var aryRet = new Array();
        '''	var cd = codes.substring(2);
        '''
        '''	aryRet[&quot;Title&quot;] = &apos;淡定“i”模式——爱符号&apos;;
        '''	var sFhs = &quot;→⇒←↑↓≠＊≧≦○◎●▲△▼▽☆★◇◆□■&quot;;
        '''	for ( var i = 0; i &lt; sFhs.length; i++ ){
        '''		aryRet[aryRet.length] = ddpyCreateCand(sFhs.substring(i, i+1));
        '''	}
        '''
        '''	return aryRet;
        '''}
        ''' 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property i符号() As String
            Get
                Return ResourceManager.GetString("i符号", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 啊	a
        '''爱	ai
        '''安	an
        '''奥	ao
        '''不	bu
        '''本	ben
        '''吧	ba
        '''并	bing
        '''被	bei
        '''别	bie
        '''报	bao
        '''表	biao
        '''白	bai
        '''办	ban
        '''帮	bang
        '''崩	beng
        '''比	bi
        '''便	bian
        '''宾	bin
        '''博	bo
        '''从	cong
        '''出	chu
        '''成	cheng
        '''长	chang
        '''此	ci
        '''才	cai
        '''车	che
        '''吃	chi
        '''产	chan
        '''重	chong
        '''查	cha
        '''擦	ca
        '''拆	chai
        '''参	can
        '''藏	cang
        '''超	chao
        '''草	cao
        '''测	ce
        '''称	chen
        '''曾	ceng
        '''抽	chou
        '''促	cu
        '''踹	chuai
        '''传	chuan
        '''窜	cuan
        '''窗	chuang
        '''吹	chui
        '''催	cui
        '''春	chun
        '''存	cun
        '''错	cou
        '''戳	chuo
        '''的	de
        '''第	di
        '''大	da
        '''代	dai
        '''到	dao
        '''得	de
        '''但	dan
        '''当	dang
        '''等	deng
        '''点	dian
        '''掉	diao
        '''跌	die
        '''顶	ding
        '''丢	diu
        '''动	dong
        '''都	dou
        '''读	du
        '''段	duan
        '''对	d [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定固顶() As String
            Get
                Return ResourceManager.GetString("淡定固顶", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 啊	a
        '''阿	a
        '''呵	a
        '''腌	a
        '''嗄	a
        '''锕	a
        '''吖	a
        '''錒	a
        '''嬶	a
        '''厑	a
        '''爱	ai
        '''碍	ai
        '''唉	ai
        '''哎	ai
        '''挨	ai
        '''埃	ai
        '''矮	ai
        '''艾	ai
        '''哀	ai
        '''蔼	ai
        '''癌	ai
        '''隘	ai
        '''霭	ai
        '''暧	ai
        '''嗳	ai
        '''捱	ai
        '''皑	ai
        '''噫	ai
        '''瑷	ai
        '''嫒	ai
        '''嗌	ai
        '''毐	ai
        '''僾	ai
        '''诶	ai
        '''锿	ai
        '''﨟	ai
        '''鴱	ai
        '''鱫	ai
        '''騃	ai
        '''馤	ai
        '''餲	ai
        '''靉	ai
        '''靄	ai
        '''阨	ai
        '''鑀	ai
        '''鎄	ai
        '''躷	ai
        '''譪	ai
        '''藹	ai
        '''薆	ai
        '''礙	ai
        '''硋	ai
        '''瞹	ai
        '''皧	ai
        '''皚	ai
        '''璦	ai
        '''濭	ai
        '''溾	ai
        '''溰	ai
        '''欸	ai
        '''曖	ai
        '''昹	ai
        '''敳	ai
        '''敱	ai
        '''懝	ai
        '''懓	ai
        '''愛	ai
        '''嬡	ai
        '''娾	ai
        '''娭	ai
        '''壒	ai
        '''塧	ai
        '''噯	ai
        '''嘊	ai
        '''啀	ai
        '''叆	ai
        '''佁	ai
        '''伌	ai
        '''魞	ai
        '''閊	ai
        '''砹	ai
        '''鱛	ai
        '''譺	ai
        '''凒	ai
        '''安	an
        '''按	an
        '''案	an
        ''' [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定字库() As String
            Get
                Return ResourceManager.GetString("淡定字库", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 阿炳	a&apos;bing
        '''阿爸	a&apos;ba
        '''阿坝	a&apos;ba
        '''阿伯	a&apos;bo
        '''阿鼻	a&apos;bi
        '''阿扁	a&apos;bian
        '''阿保	a&apos;bao
        '''阿谤	a&apos;bang
        '''阿比	a&apos;bi
        '''阿柄	a&apos;bing
        '''阿鼻地狱	a&apos;bi&apos;di&apos;yu
        '''阿鼻叫唤	a&apos;bi&apos;jiao&apos;huan
        '''阿波罗	a&apos;bo&apos;luo
        '''阿波罗计划	a&apos;bo&apos;luo&apos;ji&apos;hua
        '''阿巴拉契亚山脉	a&apos;ba&apos;la&apos;qi&apos;ya&apos;shan&apos;mai
        '''阿比让	a&apos;bi&apos;rang
        '''阿巴斯	a&apos;ba&apos;si
        '''阿坝县	a&apos;ba&apos;xian
        '''阿鼻狱	a&apos;bi&apos;yu
        '''阿坝州	a&apos;ba&apos;zhou
        '''阿坝镇	a&apos;ba&apos;zhen
        '''阿布扎比	a&apos;bu&apos;zha&apos;bi
        '''阿保之功	a&apos;bao&apos;zhi&apos;gong
        '''阿保之劳	a&apos;bao&apos;zhi&apos;lao
        '''阿茶	a&apos;cha
        '''阿从	a&apos;cong
        '''阿谄	a&apos;chan
        '''阿城市	a&apos;cheng&apos;shi
        '''阿昌族	a&apos;chang&apos;zu
        '''阿城镇	a&apos;cheng&apos;zhen
        '''阿斗	a&apos;dou
        '''阿爹	a&apos;die
        '''阿弟	a&apos;di
        '''阿大	a&apos;da
        '''吖啶	a&apos;ding
        '''阿堵	a&apos;du
        '''阿党	a&apos;dang
        '''阿殿	a&apos;dian [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 淡定词库() As String
            Get
                Return ResourceManager.GetString("淡定词库", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 // ==================================================================================
        '''// 字符串常用方法封装
        '''// ==================================================================================
        '''String.prototype.trim = function () {
        '''	return this.replace(/(^\s*)|(\s*$)/g,&quot;&quot;);
        '''} 
        '''
        '''String.prototype.leftTrim = function () {
        '''	return this.replace(/(^[\\s]*)/g, &quot;&quot;);
        '''} 
        '''
        '''String.prototype.rightTrim = function () {
        '''	return this.replace(/([\\s]*$)/g, &quot;&quot;);
        '''} 
        '''
        '''String.prototype.left = function (iLength) {
        '''	if (iLe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 脚本框架() As String
            Get
                Return ResourceManager.GetString("脚本框架", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
